### ISSUE TITLE
Expose when an existing notification id has been replaced

### ISSUE THREAD

**Issue by muhchaudhary** [astal-sh/notifd#1]
According to the [freedesktop specification](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html):

"The server must atomically (ie with no flicker or other visual cues) replace the given notification with this one. This allows clients to effectively modify the notification while it's active"

I've been using AstalNotifd in python with the provided girepository bindings and I've noticed for apps which do replace the notification ID (like Spotify) there is no signal i can hook into to get that feedback from the server. It would be nice to be able to update my notifications easily as a new notification is sent.

**Comment by Aylur** [comment]
I want to keep it minimal, so I don't want to add a `replaced` signal. I feel like the view should handle this, by keeping track of displayed notifications and do the replacing when needed.
 
should we
- add a `replaced: bool` parameter to the signal
- still emit `notified`, but instead of replacing the notification object, the existing notification object should update its properties?

I don't quite like the idea of updating notification properties, because they are still "new" notifications and we would have to decide wether to keep existing property values that were not overridden or decide on default values as a fallback

**Comment by Aylur** [comment]
added `repaced` paremeter to the `notified` signal 9812a21318abc3c508c5a6152336578d621a1032
